name: 'Forum One - Drupal Base'
description: 'Provides baseline Drupal installation typical of all Forum One build projects'
type: 'Site'

# Prompt for basic site info.
input:
  site_name:
    data_type: string
    description: The site name to be used.
    constraints:
      NotBlank: []
    prompt:
      # ask, askHidden, choice, and confirm.
      method: ask
      arguments:
        question: 'What is the site name?'
    default:
      source: 'value'
      value: 'Default Site'

  site_email:
    data_type: email
    description: The site's email address.
    constraints:
      NotBlank: []
    prompt:
      method: ask
      arguments:
        question: 'Email address to use for Drupal system mailings?'
    default:
      source: 'value'
      value: 'info@example.com'
      
# Required recipes. We always want these content and media types.
recipes:
  - core/recipes/document_media_type
  - core/recipes/image_media_type
  - core/recipes/local_video_media_type
  - core/recipes/remote_video_media_type
  - core/recipes/article_content_type
  - core/recipes/page_content_type

install:
  # Core
  - block
  - block_content
  - ckeditor5
  - config
  - contextual
  - claro
  - dblog
  - field_ui
  - filter
  - link
  - media
  - media_library
  - menu_ui
  - node
  - taxonomy
  - toolbar
  - text
  - user
  - views
  - views_ui
  # Contrib
  - admin_toolbar
  - admin_toolbar_tools
  - anchor_link
  - config_direct_save
  - config_ignore
  - config_split
  - environment_indicator
  - field_group
  - focal_point
  - linkit
  - metatag
  - pathauto
  - paragraphs
  - token

config:
  strict: false
  import:
    dblog: '*'
    linkit: '*'
    node: '*'
    media: '*'
    media_library: '*'
  actions:
    block.block.claro_admin:
      simpleConfigUpdate:
        status: false
    block.block.claro_branding:
      simpleConfigUpdate:
        status: false
    block.block.claro_tools:
      simpleConfigUpdate:
        status: false
    node.settings:
      simpleConfigUpdate:
        use_admin_theme: true
    system.theme:
      simpleConfigUpdate:
        admin: 'claro'
    system.site:
      simpleConfigUpdate:
        name: ${site_name}
        mail: ${site_email}
