name: 'Forum One - Base'
description: 'Provides baseline Drupal installation typical of all Forum One build projects'
type: 'Site'

install:
  # Core
  - block
  - block_content
  - ckeditor5
  - config
  - contextual
  - claro
  - dblog
  - field_ui
  - filter
  - link
  - media
  - media_library
  - menu_ui
  - node
  - taxonomy
  - toolbar
  - text
  - user
  - views
  - views_ui
  # Contrib
  - admin_toolbar
  - admin_toolbar_tools
  - anchor_link
  - environment_indicator
  - linkit
  - pathauto
  - paragraphs
  - token

config:
  import:
    dblog: '*'
    redirect: '*'
    node: '*'
    media: '*'
    media_library: '*'
  actions:
    block.block.claro_admin:
      simple_config_update:
        status: false
    block.block.claro_branding:
      simple_config_update:
        status: false
    block.block.claro_tools:
      simple_config_update:
        status: false
    node.settings:
      simple_config_update:
        use_admin_theme: true
    system.theme:
      simple_config_update:
        admin: 'claro'
